name: General checks

on:
  push:
    branches: [master, "release/*"]
  pull_request:
    branches: [master, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  check-precommit:
    uses: Lightning-AI/utilities/.github/workflows/check-precommit.yml@main

  check-typing:
    uses: Lightning-AI/utilities/.github/workflows/check-typing.yml@main
    with:
      actions-ref: main
      extra-typing: 'typing'

  check-schema:
    uses: Lightning-AI/utilities/.github/workflows/check-schema.yml@main
    with:
      azure-dir: ""

  check-package:
    uses: Lightning-AI/utilities/.github/workflows/check-package.yml@main
    with:
      actions-ref: main
      import-name: "fpdb"
      artifact-name: dist-packages-${{ github.sha }}
      testing-matrix: |
        {
          "os": ["ubuntu-latest", "macos-latest", "windows-latest"],
          "python-version": ["3.8", "3.10"]
        }
